# Generated by Django 5.0 on 2024-02-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='official_name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='official_name',
            field=models.TextField(unique=True),
        ),
    ]
