# Generated by Django 5.0 on 2024-01-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_authority_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
