# Generated by Django 5.0 on 2024-01-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blacklistdocuments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlackListDocuments',
            new_name='BlackListDocument',
        ),
    ]
