# Generated by Django 5.0 on 2024-01-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_blacklistdocuments_blacklistdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='contact_point',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='town',
            field=models.TextField(blank=True, null=True),
        ),
    ]
