# Generated by Django 5.0 on 2024-01-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_authority_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
