# Generated by Django 5.0 on 2024-01-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_winner_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
