# Generated by Django 5.0 on 2024-01-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_authority_email_alter_winner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='town',
            field=models.TextField(blank=True, null=True),
        ),
    ]
