# Generated by Django 5.0 on 2024-01-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_winner_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='country',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='fax',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='national_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='nuts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='postal_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='nuts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='postal_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
