# Generated by Django 5.0 on 2024-01-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_authority_country_alter_authority_fax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
